import {
  attribute as DynamoAttribute,
  autoGeneratedHashKey as DynamoAutoGeneratedHashKey,
  table as DynamoTable
} from "@aws/dynamodb-data-mapper-annotations";
import {
  ObjectType as GraphQLObjectType,
  InputType as GraphQLInputType,
  Field as GraphQLField,
  Int as GraphQLInt
} from "type-graphql";

import { Schedule, Check as CheckType } from "quickcheck";
import { Notification } from "./Notification";
import { Request } from "./Request";

@DynamoTable("Checks")
@GraphQLObjectType()
@GraphQLInputType("CheckInput")
export class Check implements CheckType {
  @DynamoAutoGeneratedHashKey()
  @GraphQLField()
  checkId: string;

  @DynamoAttribute()
  @GraphQLField()
  name: string;

  @DynamoAttribute()
  @GraphQLField()
  enabled: boolean;

  @DynamoAttribute()
  @GraphQLField()
  schedule: Schedule;

  @DynamoAttribute()
  @GraphQLField(type => GraphQLInt)
  scheduleOffsetSeconds: number;

  @DynamoAttribute()
  @GraphQLField(type => [Notification])
  notifications: Notification[];

  @DynamoAttribute()
  @GraphQLField(type => Request)
  request: Request;
}
