import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";

import { Request } from "./Request";
import { Notification } from "./Notification";
import { Schedule } from "./Schedule";

@table("Checks")
export class Check {
  @autoGeneratedHashKey()
  checkId: string;

  @attribute()
  name: string;

  @attribute()
  enabled: boolean;

  @attribute()
  schedule: Schedule;

  @attribute()
  scheduleOffsetSeconds: number;

  @attribute()
  notifications: Notification[];

  @attribute()
  request: Request;
}
