service: quickcheck-graphql

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  apiKeys:
    - quickcheck-graphql-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*Item"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - "arn:aws:dynamodb:ap-southeast-2:${env:AWS_ACCOUNT_ID}:table/*"
        - "arn:aws:dynamodb:ap-southeast-2:${env:AWS_ACCOUNT_ID}:table/*/index/*"

functions:
  graphql:
    handler: index.server
    events:
      - http:
          path: /
          method: post
          cors: true
          private: true
  playground:
    handler: index.playground
    events:
      - http:
          path: /
          method: get
          cors: true
